site:
  title: Letter Box
  start_page: letter-box::index.adoc
content:
  sources:
  - url: .
    branches: [HEAD]
    start_path: docs/
ui:
  bundle:
    # TODO: Migrate this to a live link
    url: ./docs/ui-bundle.zip
    snapshot: true