# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy
        pip install .
    - name: Lint with flake8
      run: |
        # Custom flake8 settings
        flake8 . --ignore=W503,E501 --exclude=words.py
    - name: Typecheck with mypy
      run: |
        # Parse python package name from the repo name
        # cut away owner name, and replace dashes with underscores
        REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2 | tr '-' '_')
        echo "Running MyPy on $REPO_NAME"
        mypy $REPO_NAME tests/
    - name: Test with pytest
      run: |
        pytest -vvv
